export const nationalities = {
  AU: "Australian",
  BR: "Brazilian",
  CA: "Canadian",
  CH: "Swiss",
  DE: "German",
  DK: "Danish",
  ES: "Spenish",
  FI: "Finnish",
  FR: "French",
  GB: "British",
  IE: "Irish",
  IN: "Indian",
  IR: "Iranian",
  MX: "Mexican",
  NL: "Dutch",
  NO: "Norwegian",
  NZ: "New Zealander",
  RS: "Serbian",
  TR: "Turkish",
  UA: "Ukrainian",
  US: "American",
};

export const nationalities_color = {
  AU: "pink",
  BR: "red",
  CA: "purple",
  CH: "blue",
  DE: "green",
  DK: "light-green",
  ES: "light-red",
  FI: "light-blue",
  FR: "orange",
  GB: "pink",
  IE: "red",
  IN: "purple",
  IR: "green",
  MX: "blue",
  NL: "light-green",
  NO: "light-red",
  NZ: "light-blue",
  RS: "orange",
  TR: "violet",
  UA: "pink",
  US: "red",
};
